[package]
name = "compatforge-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
compatforge-bottle = { path = "../compatforge-bottle" }
fs4 = { version = "=0.8.4", default-features = false, features = ["sync"] }
sha2.workspace = true
compatforge-domain = { path = "../compatforge-domain" }
compatforge-inspect = { path = "../compatforge-inspect" }
compatforge-orchestrator = { path = "../compatforge-orchestrator" }
compatforge-process = { path = "../compatforge-process" }
compatforge-provider-linux = { path = "../compatforge-provider-linux" }
compatforge-provider-macos = { path = "../compatforge-provider-macos" }
compatforge-storage = { path = "../compatforge-storage" }
serde.workspace = true
serde_json.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { version = "=0.38.44", features = ["net", "process", "fs"] }

[lints]
workspace = true
